"""CalibraXI data-foundation interfaces and adapters."""

from .capabilities import CapabilityRegistry, SourceManifestRegistry
from .acquisition import AcquisitionAttempt, AcquisitionCoordinator, AcquisitionResult
from .contracts import (
    CapabilityState,
    EntityType,
    HealthState,
    IngestionRun,
    IngestionRunStatus,
    QuarantineDecision,
    RawEvidence,
    SourceCapability,
    SourceCapabilityHealth,
    SourceCapabilityHealthSnapshot,
    SourceHealthSignal,
    SourceIdentity,
    SourceResult,
    FixtureMappingCandidate,
    FixtureMappingStatus,
    SourceManifest,
)
from .evidence import FileSystemRawEvidenceStore, MinioRawEvidenceStore, RawEvidenceStore, S3RawEvidenceStore
from .entity_resolution import EntityResolutionIndex, resolve_observations
from .fixture_identity import FixtureIdentityIndex
from .http_json import HttpJsonSourceAdapter, RetryPolicy, UrllibTransport
from .sofascore import SofascoreObservationParser, SofascoreSourceAdapter
from .soccerdata import (
    SOCCERDATA_PROVIDER_SPECS,
    SoccerDataAdapter,
    SoccerDataCapabilitySpec,
    SoccerDataProviderBridge,
    SoccerDataProviderSpec,
    SoccerDataQualificationMatrix,
    SoccerDataQualificationRecommendation,
    SoccerDataQualificationResult,
    SoccerDataQualificationRunner,
    default_soccerdata_provider_specs,
)
from .quality import DataQualityValidator, QualityIssue, ValidationResult
from .espn import EspnObservationParser, EspnSourceAdapter, SourceObservation
from .persistence import CanonicalAuthorityPolicy, CanonicalStore, FileSystemCanonicalStore, PersistenceResult, PostgresCanonicalStore
from .thesportsdb import TheSportsDbAdapter, TheSportsDbObservationParser, TheSportsDbSourceAdapter, TheSportsDbVerticalIngestor
from .espn_vertical import CoverageResult, EspnVerticalIngestor, VerticalIngestionReport
from .replay import replay_evidence
from .recovery import RecoveryAction, RecoveryOutcome, RecoveryWorker
from .operations import OperationalRecorder
from .scheduler import (
    EspnIngestionScheduler,
    FileProspectiveObservationStore,
    ProspectiveObservation,
    ProspectiveObservationCollector,
    SchedulerRunResult,
    SourceRateLimiter,
    SourceRatePolicy,
)
from .source_registry import default_source_manifests, qualified_capability_policies
from .bootstrap import (
    BootstrapReport,
    CoverageMetric,
    EplBootstrapper,
    EplFixture,
    EspnFixtureAcquisitionReport,
    ForecastingPostgresStore,
    ReconciliationIssue,
    build_coverage,
    audit_timezone_reconciliation,
    canonical_fixture_id,
    canonical_team_id,
    collect_espn_fixture_observations,
    derive_team_identity_map,
    epl_season_codes,
    fetch_football_data,
    parse_football_data_csv,
    reconcile_espn_fixtures,
    season_label,
)
from .forecasting import (
    BacktestResult,
    DataQualityError,
    DixonColesBaseline,
    EloBaseline,
    EligibilityBasis,
    EventDerivedEligibilityPolicy,
    EvaluationMetrics,
    FeatureSnapshot,
    FeatureSnapshotBuilder,
    FeatureSnapshotStore,
    FileFeatureSnapshotStore,
    FileForecastRunStore,
    ForecastModel,
    ForecastPrediction,
    ForecastReadService,
    ForecastRun,
    ForecastRunStore,
    FrequencyBaseline,
    MatchRecord,
    MissingState,
    ModelConfig,
    PoissonBaseline,
    ReliabilityBin,
    ScoreDistribution,
    TemperatureCalibrator,
    TemporalBacktester,
    TrainingDataset,
    TrainingExample,
    build_training_dataset,
    compare_models,
    evaluate_predictions,
)
from .historical_evaluation import (
    CalibrationComparison,
    HistoricalEvaluation,
    HistoricalPopulation,
    PowerRatingPoint,
    REAL_DATASET_MANIFEST_VERSION,
    REAL_FEATURE_SCHEMA_VERSION,
    SkippedFixture,
    build_real_historical_population,
    load_football_data_archive,
    run_real_walk_forward,
    select_production_candidate,
    write_evaluation_artifacts,
)

__all__ = [
    "CapabilityRegistry",
    "SourceManifestRegistry",
    "default_source_manifests",
    "qualified_capability_policies",
    "AcquisitionAttempt",
    "AcquisitionCoordinator",
    "AcquisitionResult",
    "CapabilityState",
    "EntityResolutionIndex",
    "resolve_observations",
    "EntityType",
    "FileSystemRawEvidenceStore",
    "S3RawEvidenceStore",
    "MinioRawEvidenceStore",
    "RawEvidenceStore",
    "HealthState",
    "IngestionRun",
    "IngestionRunStatus",
    "QuarantineDecision",
    "HttpJsonSourceAdapter",
    "RetryPolicy",
    "RawEvidence",
    "SoccerDataAdapter",
    "SoccerDataCapabilitySpec",
    "SoccerDataProviderBridge",
    "SoccerDataProviderSpec",
    "SOCCERDATA_PROVIDER_SPECS",
    "default_soccerdata_provider_specs",
    "SoccerDataQualificationMatrix",
    "SoccerDataQualificationRecommendation",
    "SoccerDataQualificationResult",
    "SoccerDataQualificationRunner",
    "SourceCapability",
    "SourceCapabilityHealth",
    "SourceCapabilityHealthSnapshot",
    "SourceHealthSignal",
    "SourceIdentity",
    "SourceResult",
    "SourceManifest",
    "FixtureMappingCandidate",
    "FixtureMappingStatus",
    "FixtureIdentityIndex",
    "DataQualityValidator",
    "QualityIssue",
    "ValidationResult",
    "UrllibTransport",
    "EspnObservationParser",
    "EspnSourceAdapter",
    "SofascoreSourceAdapter",
    "SofascoreObservationParser",
    "SourceObservation",
    "TheSportsDbObservationParser",
    "TheSportsDbSourceAdapter",
    "TheSportsDbAdapter",
    "TheSportsDbVerticalIngestor",
    "FileSystemCanonicalStore",
    "PersistenceResult",
    "CanonicalStore",
    "CanonicalAuthorityPolicy",
    "PostgresCanonicalStore",
    "EspnVerticalIngestor",
    "VerticalIngestionReport",
    "CoverageResult",
    "replay_evidence",
    "RecoveryAction",
    "RecoveryOutcome",
    "RecoveryWorker",
    "OperationalRecorder",
    "EspnIngestionScheduler",
    "SchedulerRunResult",
    "ProspectiveObservation",
    "FileProspectiveObservationStore",
    "ProspectiveObservationCollector",
    "SourceRateLimiter",
    "SourceRatePolicy",
    "BacktestResult",
    "DataQualityError",
    "DixonColesBaseline",
    "EloBaseline",
    "EligibilityBasis",
    "EventDerivedEligibilityPolicy",
    "EvaluationMetrics",
    "FeatureSnapshot",
    "FeatureSnapshotBuilder",
    "FeatureSnapshotStore",
    "FileFeatureSnapshotStore",
    "FileForecastRunStore",
    "ForecastModel",
    "ForecastPrediction",
    "ForecastReadService",
    "ForecastRun",
    "ForecastRunStore",
    "FrequencyBaseline",
    "MatchRecord",
    "MissingState",
    "ModelConfig",
    "PoissonBaseline",
    "ReliabilityBin",
    "ScoreDistribution",
    "TemperatureCalibrator",
    "TemporalBacktester",
    "TrainingDataset",
    "TrainingExample",
    "build_training_dataset",
    "compare_models",
    "evaluate_predictions",
    "CalibrationComparison",
    "HistoricalEvaluation",
    "HistoricalPopulation",
    "PowerRatingPoint",
    "REAL_DATASET_MANIFEST_VERSION",
    "REAL_FEATURE_SCHEMA_VERSION",
    "SkippedFixture",
    "audit_timezone_reconciliation",
    "build_real_historical_population",
    "load_football_data_archive",
    "run_real_walk_forward",
    "select_production_candidate",
    "write_evaluation_artifacts",
    "BootstrapReport",
    "CoverageMetric",
    "EplBootstrapper",
    "EplFixture",
    "EspnFixtureAcquisitionReport",
    "ForecastingPostgresStore",
    "ReconciliationIssue",
    "build_coverage",
    "canonical_fixture_id",
    "canonical_team_id",
    "collect_espn_fixture_observations",
    "derive_team_identity_map",
    "epl_season_codes",
    "fetch_football_data",
    "parse_football_data_csv",
    "reconcile_espn_fixtures",
    "season_label",
]
